cc_test(
    name = "dotest",
    srcs = ["test.cpp"],
    deps = [
        "//src:Args",
        "//src:Multind",
        "//src:Octal",
        "@catch2//:main",
        "@phylokit",
    ],
)

cc_test(
    name = "multind",
    srcs = ["multind.cpp"],
    deps = [
        "//src:Multind",
        "@catch2//:main",
        "@phylokit",
    ],
)
